/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Form_Lab2;
import BLL.*;
import DAL.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yuuki Nguyen
 */
public class frm_NguoiDung extends javax.swing.JFrame {

    /**
     * Creates new form KhachHang
     */
    public frm_NguoiDung() {
        initComponents();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtID1 = new java.awt.TextField();
        lblQuanLyKhachHang = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNguoiDung = new javax.swing.JTable();
        lblTieuDe = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblTen = new javax.swing.JLabel();
        lblGioiTinh = new javax.swing.JLabel();
        lblDiaChi = new javax.swing.JLabel();
        lblGhiChu = new javax.swing.JLabel();
        lblMaLoai = new javax.swing.JLabel();
        lblNgaySinh = new javax.swing.JLabel();
        lblSDT = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtHoatDong = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        txtGhiChu = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        txtTenDN = new javax.swing.JTextField();
        lblSDT1 = new javax.swing.JLabel();
        lblGhiChu1 = new javax.swing.JLabel();
        pwdMatKhau = new javax.swing.JPasswordField();
        txtSeach = new javax.swing.JTextField();
        btnSeach = new javax.swing.JButton();
        cbbMaQuyen = new javax.swing.JComboBox<>();
        cbbGioiTinh = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblQuanLyKhachHang.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblQuanLyKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuanLyKhachHang.setText("Quản Lý Người Dùng");

        tblNguoiDung.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tblNguoiDung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "ID Người Dùng", "Tên Đăng Nhập", "Mật Khẩu", "Tên Người Dùng", "Mã Quyền", "Giới Tính", "Ngày Sinh", "Hoạt Động", "Địa Chỉ", "Ghi Chú"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblNguoiDung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNguoiDungMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNguoiDung);

        lblTieuDe.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTieuDe.setText("Thông Tin Người Dùng");
        lblTieuDe.setToolTipText("");

        lblID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblID.setText("ID Người Dùng");

        lblTen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTen.setText("Tên Người Dùng");

        lblGioiTinh.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGioiTinh.setText("Giới Tính");

        lblDiaChi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDiaChi.setText("Địa Chỉ");

        lblGhiChu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGhiChu.setText("Ghi Chú");

        lblMaLoai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMaLoai.setText("Mã Quyền");

        lblNgaySinh.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNgaySinh.setText("Ngày Sinh");

        lblSDT.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSDT.setText("Hoạt Động");

        btnThem.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setBorder(null);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setBorder(null);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setBorder(null);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        lblSDT1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSDT1.setText("Tên Đăng Nhập");

        lblGhiChu1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGhiChu1.setText("Mật Khẩu");

        txtSeach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSeachKeyReleased(evt);
            }
        });

        btnSeach.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSeach.setText("Tìm Kiếm");
        btnSeach.setBorder(null);

        cbbMaQuyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(lblTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(lblTen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                                    .addComponent(lblID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lblMaLoai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(40, 40, 40)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtID)
                                                    .addComponent(txtTen)
                                                    .addComponent(cbbMaQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lblGhiChu1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblSDT1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(40, 40, 40)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtTenDN, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                                                    .addComponent(pwdMatKhau))))
                                        .addGap(42, 42, 42)
                                        .addComponent(lblGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtGhiChu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbbGioiTinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtHoatDong, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtDiaChi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)))))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblQuanLyKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(txtSeach, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnSeach, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuanLyKhachHang)
                    .addComponent(txtSeach, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeach, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lblTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbbGioiTinh)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblGhiChu1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSDT1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenDN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addComponent(pwdMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbbMaQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHoatDong, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(lblSDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDiaChi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblGhiChu)
                            .addComponent(txtGhiChu, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 
    private void txtSeachKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSeachKeyReleased
        // TODO add your handling code here:
        
        
        
           String seach =  txtSeach.getText();
                      
        ResultSet rs =BLL_NguoiDung.TimKiem(seach);
        BLL_NguoiDung.DODuLieuTimKiem(rs, tblNguoiDung);
        
//        String Seach = "select * from NguoiDung where HoTen like N'%" + seach+"%'"
//                + " or DiaChi like N'%"+ seach + "%' or Day(NgaySinh) like '%"+ seach+"%'";
//           
// DefaultTableModel table = (DefaultTableModel)tblNguoiDung.getModel();  
//        table.setRowCount(0);
//        
//        try {
//           
//            ResultSet rs = Lab2_735_821.conn.ExcuteQuerySelect(Seach);
//
//            while(rs.next()){
//                Object[] item = new Object[11];
//                int a = table.getRowCount();
//                item[0] = a+1;
//                item[1] = rs.getString("Ma");
//                item[2] = rs.getString("Ten");
//                item[3] = rs.getString("MatKhau");
//                item[4] = rs.getString("HoTen");
//                item[5] = rs.getString("MaQuyen");
//                item[6] = rs.getString("GioiTinh"); 
//                item[7] = DateFormatString.getDateString(rs.getDate("NgaySinh"));               
//                item[8] = rs.getString("HoatDong");
//                item[9] = rs.getString("DiaChi");
//                item[10] = rs.getString("GhiChu");
//                              
//                table.addRow(item);
//            }
//        } catch (SQLException ex) {
//            System.out.println("lỗi truy vấn: " + ex.getMessage());
//        }

     
       
    }//GEN-LAST:event_txtSeachKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        DefaultTableModel table = (DefaultTableModel)tblNguoiDung.getModel();
        BLL.BLL_NguoiDung.DuLieuDatabase(table);
        DefaultComboBoxModel cbbModel = new DefaultComboBoxModel();
        BLL_NguoiDung.DoDuLieuVaoCombobox(cbbModel);
          cbbMaQuyen.setModel(cbbModel);
       
  
    }//GEN-LAST:event_formWindowOpened

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
             MyCombobox cbb = (MyCombobox)cbbMaQuyen.getSelectedItem();
                 BLL_NguoiDung.Them_ND( 
                (String)cbb.Value,
                 cbbGioiTinh.getSelectedIndex(),
                 txtHoatDong.getText(),
                 txtTenDN.getText(),
                 pwdMatKhau.getText(), txtTen.getText(),
                 txtNgaySinh.getText(),
                 txtDiaChi.getText(),txtGhiChu.getText());
                 DefaultTableModel table = (DefaultTableModel)tblNguoiDung.getModel();
                 BLL.BLL_NguoiDung.DuLieuDatabase(table);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
         int LuaChon = JOptionPane.showConfirmDialog(new JFrame(),"Thông Báo xác nhận",
                 "Bạn có chắc chắn xóa không?" , JOptionPane.YES_NO_OPTION);
       
       if (LuaChon == JOptionPane.YES_OPTION){
           
        int CacDongDuocChon[] = tblNguoiDung.getSelectedRows();
        ArrayList<String> mangMaLoai = new ArrayList<>();
        
        for( int i = 0; i< CacDongDuocChon.length; i++){
            mangMaLoai.add(tblNguoiDung.getValueAt(CacDongDuocChon[i], 1).toString());
        }
        // gọi hàm xóa 
        BLL_NguoiDung.Xoa_ND(mangMaLoai);
        
        DefaultTableModel table = (DefaultTableModel)tblNguoiDung.getModel();
        BLL.BLL_NguoiDung.DuLieuDatabase(table);
       }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        MyCombobox cbb = (MyCombobox)cbbMaQuyen.getSelectedItem();
         BLL_NguoiDung.Sua_ND( txtID.getText(),
                (String)cbb.Value,
                 cbbGioiTinh.getSelectedIndex(),
                 txtHoatDong.getText(),
                 txtTenDN.getText(),
                 pwdMatKhau.getText(), txtTen.getText(),
                 txtNgaySinh.getText(),
                 txtDiaChi.getText(),txtGhiChu.getText());
         DefaultTableModel table = (DefaultTableModel)tblNguoiDung.getModel();
        BLL.BLL_NguoiDung.DuLieuDatabase(table);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tblNguoiDungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNguoiDungMouseClicked
        // TODO add your handling code here:
        
          int viTriDong = tblNguoiDung.getSelectedRow();    
        
       
        String ID = tblNguoiDung.getValueAt(viTriDong, 1).toString();
        txtID.setText(ID);
        
        String TenDN = tblNguoiDung.getValueAt(viTriDong, 2).toString();
        txtTenDN.setText(TenDN);
               
        String MatKhau = tblNguoiDung.getValueAt(viTriDong, 3).toString();
        pwdMatKhau.setText(MatKhau);
        
        String Ten = tblNguoiDung.getValueAt(viTriDong, 4).toString();
        txtTen.setText(Ten);
        
        String Quyen = tblNguoiDung.getValueAt(viTriDong, 5).toString();
        SetCbbLoaiNguoiDung(Quyen);
                
        String gt = tblNguoiDung.getValueAt(viTriDong, 6).toString();
        int GioiTinh = Integer.parseInt(gt);
        cbbGioiTinh.setSelectedIndex(GioiTinh);
        
        String NgaySinh = tblNguoiDung.getValueAt(viTriDong, 7).toString();
        txtNgaySinh.setText(NgaySinh);
                
        String HoatDong = tblNguoiDung.getValueAt(viTriDong, 8).toString();
        txtHoatDong.setText(HoatDong);
        
        String DiaChi = tblNguoiDung.getValueAt(viTriDong, 9).toString();
        txtDiaChi.setText(DiaChi);
        
        String GhiChu = tblNguoiDung.getValueAt(viTriDong, 10).toString();
        txtGhiChu.setText(GhiChu);
        
        
    }//GEN-LAST:event_tblNguoiDungMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
         int luachon = JOptionPane.showConfirmDialog(new JFrame(), "Bạn có muốn thoát không ?",
                "Thông báo thoát ", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        
        if(luachon == JOptionPane.YES_OPTION){
               this.hide();
               frm_Main frm = new frm_Main();
               frm.show();
        }
        else{
            // không thực hiện lệnh xóa
        }
    }//GEN-LAST:event_formWindowClosing
 
    private void SetCbbLoaiNguoiDung(String tenLoai){
        for(int i = 0; i < cbbMaQuyen.getItemCount();i++){
            
            // Lấy item obj ở trên về Mycombobox
            Object obj = cbbMaQuyen.getItemAt(i);
            
            // Ép kiểu của obj ở trên về Mycombobox
            MyCombobox cbb = (MyCombobox)obj;            
            
            // Kiểm tra tên của cái cbb có bằng vs cái set lại hay k?
            if(cbb.Value.equals(tenLoai)){
                cbbMaQuyen.setSelectedIndex(i);
            }
            
        }
    }
   
//    private void DoDuLieuVaoCombobox(){
//        try {
//            String query = "Select * from QuyenNguoiDung";
//            ResultSet rs = Lab2_735_821.conn.ExcuteQuerySelect(query);
//            DefaultComboBoxModel cbbModel = new DefaultComboBoxModel();
//            while(rs.next()){
//                MyCombobox item = new MyCombobox(rs.getString("TenQuyen"), 
//                        rs.getString("MaQuyen"));
//                cbbModel.addElement(item);
//            }
//            cbbMaQuyen.setModel(cbbModel);
//            
//        } catch (SQLException ex) {
//            System.out.println("Lỗi truy vấn" + ex.getMessage());
//        }
//    }
   
    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeach;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbGioiTinh;
    private javax.swing.JComboBox<String> cbbMaQuyen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblGhiChu;
    private javax.swing.JLabel lblGhiChu1;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMaLoai;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblQuanLyKhachHang;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblSDT1;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JPasswordField pwdMatKhau;
    private javax.swing.JTable tblNguoiDung;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtHoatDong;
    private javax.swing.JTextField txtID;
    private java.awt.TextField txtID1;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSeach;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTenDN;
    // End of variables declaration//GEN-END:variables
}
